server:
  port: 7653

spring:
  application:
    name: Consumer

dubbo:
  application:
    name: Consumer
  registry:
    address: zookeeper://tx.me:2181
    client: curator
  monitor:
    # 从注册中心发现监控中心地址
    protocol: registry
    # 直连监控中心服务器地址
    # address: tx.me:2181

## 版本配置
user:
  service:
    v1_0_0: 1.0.0
