server:
  port: 7653

spring:
  application:
    name: Consumer

dubbo:
  application:
    name: Consumer
  registry:
    address: zookeeper://tx.me:2181
    client: curator
  # 关闭消费方的启动时检查（启动时检查不到依赖的provider就抛出 IllegalStateException 异常）
  consumer:
    check: false
#    register: false


## 版本配置
user:
  service:
    v1_0_0: 1.0.0
