server:
  port: 7653

spring:
  application:
    name: Consumer

dubbo:
  application:
    name: Consumer
  registry:
    address: zookeeper://tx.me:2181
    client: curator
#    register: false

## 版本配置
user:
  service:
    v1_0_0: 1.0.0
